### ISSUE TITLE
lizzy-client deletes newly created stack when --keep-stacks 1 option is specified

### ISSUE THREAD

**Issue by dmitrykrivaltsevich** [zalando/lizzy-client#14]
I had 2 stack already deployed by lizzy.

When I used the command in a third time
```bash
$ lizzy create --keep-stacks 1 --traffic 100 my-app.yaml 1.0
```

I saw in logs:

---
Wating for new stack.. . . . . . Stack was removed before deployment finished.

---
Cloud Formation events also shows that stack was immediately deleted by lizzy after deployment

**Comment by jmcs** [comment]
This is caused by zalando/lizzy#73 please follow that issue.
