### ISSUE TITLE
Keep stacks if parameter --keep-stacks is missing

### ISSUE THREAD

**Issue by rwitzel** [zalando/lizzy-client#48]
Current behaviour:

When `lizzy create` is called without parameter `--keep-stacks`, all old stacks are deleted.

Desired behaviour:

When `lizzy create` is called without parameter `--keep-stacks`, all stacks are kept as they are.

**Comment by jmcs** [comment]
That's already [planned for the next version of lizzy](https://github.com/zalando/lizzy-client/blob/ee969e2dc0b023821b164717d51c25d6d121aee2/lizzy_client/cli.py#L156), I was just too lazy to create the ticket (thanks for doing it for me).
In the mean time, as a workaround just use a very high number.

**Comment by jmcs** [comment]
Fixed in #56.
