### ISSUE TITLE
Default for --traffic should be zero not 100

### ISSUE THREAD

**Issue by rwitzel** [zalando/lizzy-client#49]
Current behaviour:

If for command `lizzy create` parameter `--traffic` is not passed, the traffic is switched entirely.

Desired behaviour:

If for command `lizzy create` parameter `--traffic` is not passed, the traffic is not switched at all.

Reasoning:
According to the principle of least surprise, a command called `create` should not do something else by default.

**Comment by jmcs** [comment]
Fixed in #56.
