### ISSUE TITLE
Vendorize dependencies

### ISSUE THREAD

**Issue by rafaelcaricio** [zalando/lizzy-client#53]
Since lizzy-client is a command line tool we should think about vendorizing the dependencies to prevent users having problems with conflicts. Most of the time the users do not have enough knowledge of Python development to understand how to solve those conflicts.

**Comment by hjacobs** [comment]
Oh no, another vendorizing attempt :disappointed: 

Most people should now use the Docker "toolchain" images which contain Lizzy Client pre-installed, so no problems (e.g. on CI/CD).

**Comment by rafaelcaricio** [comment]
In this case of using it in a toolchain I totally agree. Maybe it is not a big deal for this project specifically. But anything that needs user to install locally and use locally in their own machines we should isolate the installation and dependencies as much as we can.
