### ISSUE TITLE
lizzy-client installation makes senza unusable

### ISSUE THREAD

**Issue by ChristianLohmann** [zalando/lizzy-client#77]
If someone installs lizzy-client on an environment where senza is already installed then lizzy-client would somehow overwrite senza and makes it unusable.

**Comment by rafaelcaricio** [comment]
Why would you install Lizzy-client and Senza locally?

**Comment by ChristianLohmann** [comment]
It happened in our CD toolchains where lizzy client AND senza was installed, and besides that, it doesn't matter if i would install lizzy-client locally or not. The fact is that lizzy-client corrupts a fully functional senza installation.

**Comment by rafaelcaricio** [comment]
Ok. Thanks for being so nice.

**Comment by jmcs** [comment]
The reason why it does it is to allow people to just copy-paste the commands they run locally and run them on their CI environment, so lizzy-client needs to overwrite the senza command. On the long term the plan is to merge senza and lizzy-client but senza still needs to be refactored before that.

Is there any reason why you need senza installed on your toolchain? We can probably implement it in lizzy and remove your need to have senza installed if you create an issue for it.

**Comment by prayerslayer** [comment]
> so lizzy-client needs to overwrite the senza command

Hi, I'm not so proficient in Python. Could you elaborate on what the alternatives were and why they didn't fit?

Thanks 🙌

**Comment by jmcs** [comment]
@prayerslayer the only way to allow someone to copy "senza create ..." from their local machine to their CI environment and having lizzy handle it seamlessly is for lizzy-client to pretend it's senza.

**Comment by prayerslayer** [comment]
And what about offering the same API as senza commands, but using `lizzy` and not touching `senza` (but maybe calling it under the hodd) so people can easily search & replace on their scripts?

**Comment by hjacobs** [comment]
Hmm, why couldn't you just add an alias in the CI environment to emulate `senza`? I still want to be able to install `lizzy-client` locally (even if it's only for debugging, playing around) without corrupting Senza...
