### ISSUE TITLE
lizzy doesn't support ELB V2

### ISSUE THREAD

**Issue by crack-king** [zalando/lizzy-client#78]
Hi, 

I tried to use the ELB V2 in my senza.yaml file, but lizzy couldn't deploy my application. I got the following error: 

`Generating Cloud Formation template.. EXCEPTION OCCURRED: Component "Senza::WeightedDnsElasticLoadBalancerV2" does not exist`

**Comment by rafaelcaricio** [comment]
@crack-king new version of Lizzy image should be created with latest Senza version. Please use Zalando's internal communication tools for this kind of support.
