### ISSUE TITLE
For traffic command, lizzy client should wait until stack becomes UPDATE_COMPLETE state to return

### ISSUE THREAD

**Issue by ignacio-ifm** [zalando/lizzy-client#85]
Now lizzy traffic does not wait for the stack to become status UPDATE_COMPLETE, which means next steps in pipeline that assume the traffic is switched will fail or perform actions to the wrong stack. Please make it possible to make lizzy wait for this state before returning (by default would be the best, but an option would be good too).

**Comment by rafaelcaricio** [comment]
Should be fixed by https://github.com/zalando-stups/senza/issues/398

**Comment by rafaelcaricio** [comment]
It will be fixed after https://github.com/zalando-stups/senza/pull/409 gets merged.
